spring:
  application:
    name: account-service
  datasource:
    url: jdbc:h2:mem:accountdb
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

    spring:
      threads:
        virtual:
          enabled: true

server:
  port: 8081